---
deployment:
  tasks:
    - export DEPLOYPATH=/home/your_cpanel_username/public_html/liff-be

    # Copy public assets
    - /bin/cp -R public/* $DEPLOYPATH

    # Run composer install (if vendor changes)
    - /usr/local/bin/php /home/username/repositories/liff-be/composer.phar install --no-dev --optimize-autoloader

    # Clear and cache configs/routes
    - /usr/local/bin/php /home/username/repositories/liff-be/artisan config:cache
    - /usr/local/bin/php /home/username/repositories/liff-be/artisan route:cache
